
-- =====================================================
-- Hospital Management System
-- Seed Data
-- =====================================================

USE hospital_management_system;

-- NOTE:
-- Replace the password hash below with one generated by bcrypt
-- in your Node.js application before using in production.
-- Example:
-- const bcrypt = require('bcrypt');
-- bcrypt.hash('admin', 10);

INSERT INTO users
(name, email, password, role, status)
VALUES
(
'System Administrator',
'admin@hospital.com',
'$2b$10$REPLACE_WITH_GENERATED_BCRYPT_HASH',
'ADMIN',
'ACTIVE'
);

INSERT INTO doctor_categories (category_name, description)
VALUES
('General Physician','General medical care'),
('Dermatologist','Skin specialist'),
('Orthopedic','Bone and joint specialist'),
('Neurologist','Brain and nervous system specialist'),
('Cardiologist','Heart specialist'),
('Eye Specialist','Ophthalmology specialist'),
('ENT Specialist','Ear, Nose and Throat specialist'),
('Dentist','Dental specialist'),
('Pediatrician','Child specialist'),
('Psychiatrist','Mental health specialist');

-- -----------------------------------------------------
-- OPTIONAL SAMPLE DATA
-- Uncomment after implementing authentication.
-- -----------------------------------------------------

/*
INSERT INTO users
(name,email,password,role,status)
VALUES
('Dr. John Doe','john@hospital.com','<bcrypt_hash>','DOCTOR','ACTIVE'),
('Alice Smith','alice@example.com','<bcrypt_hash>','PATIENT','ACTIVE');

-- Create matching doctor_profile and patient_profile
-- after replacing user IDs with the generated IDs.
*/
